# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number_of_reads', models.IntegerField(default=0)),
                ('article', models.FileField(upload_to='article/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CameraFeatures',
            fields=[
                ('cf_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=100)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('gen_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Intrested_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Participates_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('caption', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='image/%Y/%m/%d')),
                ('number_of_downloads', models.IntegerField(default=0)),
                ('file_type', models.CharField(max_length=10)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.DurationField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Features',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('features', models.CharField(max_length=100)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number_of_likes', models.IntegerField(default=0)),
                ('number_of_share', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Review_About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_date', models.CharField(max_length=12)),
                ('a_date', models.CharField(max_length=12)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Photo')),
                ('rev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribes_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=12)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('u_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('m_init', models.CharField(blank=True, max_length=5, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('username', models.CharField(max_length=8)),
                ('dob', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=8)),
                ('gender', models.CharField(default='F', max_length=1)),
                ('phone', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Tutorials',
            fields=[
                ('Tut_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='video/%Y/%m/%d')),
                ('number_of_views', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('w_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.CharField(max_length=12)),
                ('duration', models.DurationField(default=1)),
                ('organisation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_Requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=100)),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Workshop')),
            ],
        ),
        migrations.AddField(
            model_name='subscribes_to',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='participates_in',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='participates_in',
            name='w_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Workshop'),
        ),
        migrations.AddField(
            model_name='intrested_in',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='follows',
            name='followed_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Followed', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='follows',
            name='follower_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='editor',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Photo'),
        ),
        migrations.AddField(
            model_name='editor',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='comments',
            name='review_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Review'),
        ),
        migrations.AddField(
            model_name='camera',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='plan_features',
            unique_together=set([('plan_id', 'features')]),
        ),
        migrations.AlterUniqueTogether(
            name='follows',
            unique_together=set([('followed_id', 'follower_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='editor',
            unique_together=set([('user_id', 'p_id')]),
        ),
    ]
