# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170319_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo_id',
            field=models.ForeignKey(default='ph01', on_delete=django.db.models.deletion.CASCADE, to='blog.Photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='gen_id',
            field=models.ForeignKey(default='gen01', on_delete=django.db.models.deletion.CASCADE, to='blog.Genre'),
            preserve_default=False,
        ),
    ]
