# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170320_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='u_id',
            field=models.CharField(blank=True, max_length=30, primary_key=True, serialize=False),
        ),
    ]
